global using System;
global using System.Collections.Generic;
global using System.Text;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.ComponentModel.DataAnnotations;
global using Spire.Doc;
global using System.Security.Cryptography;
global using Microsoft.EntityFrameworkCore;
global using SzamitogepNyilvantarto.Data.Entities;