// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzamitogepNyilvantarto.Data;

#nullable disable

namespace SzamitogepNyilvantarto.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230410055046_hibaError2")]
    partial class hibaError2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SzamitogepNyilvantarto.Data.Entities.Allapot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Elnevezes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Allapotok");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Elnevezes = "Használatban"
                        },
                        new
                        {
                            Id = 2,
                            Elnevezes = "Használatra kész"
                        },
                        new
                        {
                            Id = 3,
                            Elnevezes = "Hibás"
                        },
                        new
                        {
                            Id = 4,
                            Elnevezes = "Javítás alatt"
                        },
                        new
                        {
                            Id = 5,
                            Elnevezes = "Leselejtezve"
                        },
                        new
                        {
                            Id = 6,
                            Elnevezes = "Megoldódott"
                        });
                });

            modelBuilder.Entity("SzamitogepNyilvantarto.Data.Entities.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DokumentumTipus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelhasznaloNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Felhasznalok");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DokumentumTipus = "pdf",
                            FelhasznaloNev = "Admin",
                            Jelszo = "136115117218236981692404550166601582019910026154138662282501431011442351461411516818112318151222934126776423914526192488911188226191219120166324018314414820623266861245"
                        });
                });

            modelBuilder.Entity("SzamitogepNyilvantarto.Data.Entities.Hiba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AllapotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BejelentesDatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CsereGepId")
                        .HasColumnType("int");

                    b.Property<string>("HibaLeiras")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HibasGepId")
                        .HasColumnType("int");

                    b.Property<string>("JavitasLeiras")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Terem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisszakerulesDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AllapotId");

                    b.HasIndex("CsereGepId");

                    b.HasIndex("HibasGepId");

                    b.ToTable("Hibak");
                });

            modelBuilder.Entity("SzamitogepNyilvantarto.Data.Entities.Szamitogep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllapotId")
                        .HasColumnType("int");

                    b.Property<string>("Azonosito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HatertarMerete")
                        .HasColumnType("int");

                    b.Property<string>("HattertarTipusa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("MemoriaMerete")
                        .HasColumnType("int");

                    b.Property<string>("MemoriaTipusa")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Processzor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Terem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AllapotId");

                    b.ToTable("Szamitogepek");
                });

            modelBuilder.Entity("SzamitogepNyilvantarto.Data.Entities.Hiba", b =>
                {
                    b.HasOne("SzamitogepNyilvantarto.Data.Entities.Allapot", "Allapot")
                        .WithMany("Hibak")
                        .HasForeignKey("AllapotId");

                    b.HasOne("SzamitogepNyilvantarto.Data.Entities.Szamitogep", "CsereGep")
                        .WithMany("Cserek")
                        .HasForeignKey("CsereGepId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SzamitogepNyilvantarto.Data.Entities.Szamitogep", "HibasGep")
                        .WithMany("Hibak")
                        .HasForeignKey("HibasGepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Allapot");

                    b.Navigation("CsereGep");

                    b.Navigation("HibasGep");
                });

            modelBuilder.Entity("SzamitogepNyilvantarto.Data.Entities.Szamitogep", b =>
                {
                    b.HasOne("SzamitogepNyilvantarto.Data.Entities.Allapot", "Allapot")
                        .WithMany("Szamitogepek")
                        .HasForeignKey("AllapotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Allapot");
                });

            modelBuilder.Entity("SzamitogepNyilvantarto.Data.Entities.Allapot", b =>
                {
                    b.Navigation("Hibak");

                    b.Navigation("Szamitogepek");
                });

            modelBuilder.Entity("SzamitogepNyilvantarto.Data.Entities.Szamitogep", b =>
                {
                    b.Navigation("Cserek");

                    b.Navigation("Hibak");
                });
#pragma warning restore 612, 618
        }
    }
}
