global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.ComponentModel.DataAnnotations;
global using SzamitogepNyilvantarto.Data.Entities;
global using System.Globalization;
global using SzamitogepNyilvantarto.Data;
global using SzamitogepNyilvantarto.UI.ViewModels;
global using static SzamitogepNyilvantarto.UI.Extensions.ObjectExtensions;
global using Microsoft.EntityFrameworkCore;
global using SzamitogepNyilvantarto.UI.Enums;
global using RazorLight;
global using Spire.Doc;
global using System.Reflection;
global using RazorLight;
global using System.Reflection;
global using WkHtmlToPdfDotNet;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using SzamitogepNyilvantarto.Data.Entities;
global using static System.Runtime.InteropServices.JavaScript.JSType;
global using System.Data;
global using SzamitogepNyilvantarto.UI.DocumentGenerators;
global using SzamitogepNyilvantarto.UI.MenuControls;
global using SzamitogepNyilvantarto.UI.MenuControls.Hiba;
global using SzamitogepNyilvantarto.UI.MenuControls.Reports;
global using SzamitogepNyilvantarto.UI.MenuControls.Szamitogep;